### PR TITLE
Feature/myfeature

### PR DESCRIPTION
**Pull request by tnyandoro**
> Created my My Library HTML/CSS and JS files.
> All of my book objects are going to be stored in a simple array, so add a function to the script (not the constructor) that can take the user’s input and store the new book objects into an array. 
> I have Written a function that loops through the array and displays each book on the page and displays them in some sort of table,
> I have provided a form allowing users to input the details for the new book: author, title, number of pages, whether it’s been read and anything else you might want.
> I have added a button on each book’s display to remove the book from the library.
> I have associated your DOM elements with the actual book objects in some way. One easy solution is giving them a data-attribute that corresponds to the index of the library array.
> Added a local storage function so the books don't disappear on page reload.

### CODE REVIEW

**Comment by bertil291utn** [comment]
# **Status:** Invalid 🚫

## Hey guys I hope you're having a great time

I see all your effort work on this project however I have to invalid due to: 

- Edit this pull request should come from a feature to the development branch 
- Update README file following this [example](https://github.com/microverseinc/readme-template)
- Add linters workflow config files, following this [example](https://github.com/microverseinc/linters-config/tree/master/javascript) 



<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: Invalid🚫**

Hello team, great work on the project. However I have to mark it as invalid. As requested by the previous TSE, with git flow, the PR must be requesting to getting merge in develop branch not main branch.

Kindly fix and ask for another review.

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @tnyandoro  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: The app is working as it should except few issues which are listed below
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Fix the microverse link from readme file currently it's broken
- [ ] Add a live demo link in your readme file
- [ ] Add how the getting started section on your readme file: explain how to install, and setup and usage of this project on a local environment
- [ ] There is a bug in book display, it's mismapping the values to the titles in the table: The title is being shown in place of Author and vice versa => fix that issue
- [ ] It should have a `New Book button` which upon clicking it should bring up a form => currently your form is shown by default
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by tnyandoro** [comment]
> Bug of Mix Title and Author fixed
> Live Demo Added
> Show and Hide form Added

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @tnyandoro :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
